#!/usr/bin/env nextflow

include { PREPARE_BAKTA } from '../modules/bakta'
include { PACK_SQUASHFS } from '../modules/squashfs'
include {
    databaseImageIsValid
    managedDatabaseImageIsValid
} from '../lib/validation'


workflow RESOLVE_BAKTA_DB {

    main:

    /*
     * If --bakta_db is provided, use it.
     * Otherwise, look for the versioned database generated by BenchAnnot.
     */
    def expectedDb = params.bakta_db \
        ? params.bakta_db \
        : "${projectDir}/data/database/bakta/bakta_${params.bakta_db_version}.sqsh"

    /*
     * External user-provided databases only require basic validation.
     * BenchAnnot-managed databases require the integrity metadata as well.
     */
    def dbIsValid = params.bakta_db \
        ? databaseImageIsValid(expectedDb) \
        : managedDatabaseImageIsValid(expectedDb)


    if (dbIsValid) {

        log.info "Using existing Bakta database: ${expectedDb}"

        bakta_db_ch = channel.value(
            file(expectedDb)
        )

    } else {

        log.info "Bakta database image not found or incomplete. Preparing Bakta DB ${params.bakta_db_version}..."

        def cacheDir = file(
            "${projectDir}/data/database/bakta/download"
        )

        cacheDir.mkdirs()

        prepared = PREPARE_BAKTA(
            cacheDir.toString()
        )

        packed = PACK_SQUASHFS(
            prepared.database_dir,
            'bakta',
            "bakta_${params.bakta_db_version}"
        )

        /*
         * PACK_SQUASHFS emits:
         * tuple(database_name, database_image)
         *
         * Downstream BAKTA expects only the database image path.
         */
        bakta_db_ch = packed.database.map {
            database_name, database_image ->
                database_image
        }
    }


    emit:

    database = bakta_db_ch
}
